/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Loading: typeof import('./../src/components/common/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSuspense: typeof import('./../src/components/common/RouterSuspense.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
